### ISSUE TITLE
jboss-as-jms-client-bom-7.3.0.Final-redhat-5.pom. Error code 500, Internal Server Error

### ISSUE THREAD

**Issue by isnuryusuf** [jboss-eap/quickstart#111]
Failed to execute goal on project jboss-as-helloworld-jms: Could not resolve dependencies for project org.jboss.as.quickstarts:jboss-as-helloworld-jms:jar:7.1.2-SNAPSHOT: Failed to collect dependencies at org.jboss.as:jboss-as-jms-client-bom:pom:7.3.0.Final-redhat-5: Failed to read artifact descriptor for org.jboss.as:jboss-as-jms-client-bom:pom:7.3.0.Final-redhat-5: Could not transfer artifact org.jboss.as:jboss-as-jms-client-bom:pom:7.3.0.Final-redhat-5 from/to redhat-ga-repository (http://maven.repository.redhat.com/ga/): Failed to transfer http://maven.repository.redhat.com/ga/org/jboss/as/jboss-as-jms-client-bom/7.3.0.Final-redhat-5/jboss-as-jms-client-bom-7.3.0.Final-redhat-5.pom. Error code 500, Internal Server Error -> [Help 1]

**Comment by sgilda** [comment]
@isnuryusuf : This repository is not valid.

You might want to try the quickstarts that ship with the product [1].
Also, the WildFly quickstarts [2] are the quickstarts that are currently under development.

[1] https://developers.redhat.com/products/eap/download/
[2] https://github.com/wildfly/quickstart

**Comment by isnuryusuf** [comment]
thnks
