### ISSUE TITLE
kitchensink-ear deployments require package and jboss-as:deploy goals

### ISSUE THREAD

**Issue by miclark** [jboss-eap/quickstart#3]
The kitchensink-ear README.md says to run mvn package then mvn jboss-as:deploy however that fails.  Seems like package must be used in conjunction with deploy, ie: mvn package jboss-as:deploy  The same goes for undeploy, has to be mvn package jboss-as:undeploy.

**Comment by sgilda** [comment]
I just tried it with the latest code base. Everything seems to work fine.

I ran: mvn clean package
The result was BUILD SUCCESS

I then ran: mvn jboss-as:deploy
Again, the result was BUILD SUCCESS and I see this is the server console:
    16:06:51,336 INFO  [org.jboss.web](MSC service thread 1-3) JBAS018210: Registering web context: /jboss-as-kitchensink-ear-web
    16:06:51,371 INFO  [org.jboss.as.server](management-handler-threads - 3) JBAS018559: Deployed "jboss-as-kitchensink-ear.ear"

I am able to browse to http://localhost:8080/jboss-as-kitchensink-ear-web/index.jsf and run the application. 

Can you please try it again with the current code base?

**Comment by sgilda** [comment]
Mike, 
I am closing this issue because it is now obsolete. The README files now all say to run: "mvn clean package jboss-as:deploy". Please let me know if you object. :-)

Sande

**Comment by miclark** [comment]
No objection.
